# Generated by Django 4.0.6 on 2022-07-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='spattack',
            new_name='spAttack',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='spdefense',
            new_name='spDefense',
        ),
    ]
